# Generated by Django 5.0.4 on 2024-05-14 14:50

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_options_alter_comment_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uploaded_report',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.user_directory_path),
        ),
    ]
