# Generated by Django 5.0.4 on 2024-05-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_uploaded_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='generated_pdf',
            field=models.FileField(blank=True, null=True, upload_to='generated_pdfs/'),
        ),
    ]
