# Generated by Django 5.0.4 on 2024-05-18 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_control', models.CharField(default='', max_length=5000)),
                ('subcontrol', models.CharField(default='', max_length=5000)),
                ('control_details', models.CharField(default='', max_length=5000)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likelihood', models.IntegerField(default=0)),
                ('impact', models.IntegerField(default=0)),
                ('exposure', models.IntegerField(default=0)),
                ('risk_level', models.CharField(default='', max_length=5000)),
                ('risk_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskassesment.riskassessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
